In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
style.use('fivethirtyeight')

#put the contents of the csv file into a variable object
soccer_stats = pd.read_csv('fifa19_kaggle.csv')

# select only first 5 rows
df = soccer_stats.head(10)

# select only listed columns
sd = df.reindex(columns=['Name', 'Age', 'Nationality', 'Overall', 'Club'])

# check dataset
print(sd)

sd.plot(kind='bar')

plt.title("fifa visual")
plt.xlabel("age")
plt.ylabel("skill")
plt.show()

                Name  Age Nationality  Overall                 Club
0           L. Messi   31   Argentina       94         FC Barcelona
1  Cristiano Ronaldo   33    Portugal       94             Juventus
2          Neymar Jr   26      Brazil       92  Paris Saint-Germain
3             De Gea   27       Spain       91    Manchester United
4       K. De Bruyne   27     Belgium       91      Manchester City
5          E. Hazard   27     Belgium       91              Chelsea
6          L. Modrić   32     Croatia       91          Real Madrid
7          L. Suárez   31     Uruguay       91         FC Barcelona
8       Sergio Ramos   32       Spain       91          Real Madrid
9           J. Oblak   25    Slovenia       90      Atlético Madrid

In [19]:
df.describe()

,Unnamed: 0,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.0000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.00000,10.000000
mean,4.50000,164887.100000,29.100000,91.600000,92.300000,2062.500000,4.300000,3.900000,3.400000,8.0000,...,69.900000,85.300000,44.100000,41.400000,38.800000,27.500000,27.500000,26.800000,29.10000,29.100000
std,3.02765,52737.251682,2.960856,1.349897,1.251666,355.780597,0.674949,0.737865,1.429841,4.2947,...,24.682202,9.832486,23.335476,26.086182,25.542122,32.428554,32.544841,30.363721,31.85889,33.991666
min,0.00000,20801.000000,25.000000,90.000000,91.000000,1331.000000,3.000000,3.000000,1.000000,1.0000,...,11.000000,68.000000,15.000000,12.000000,13.000000,6.000000,8.000000,5.000000,7.00000,8.000000
25%,2.25000,162662.250000,27.000000,91.000000,91.000000,2142.250000,4.000000,3.250000,3.000000,7.0000,...,75.000000,82.500000,27.250000,24.750000,22.250000,9.500000,9.500000,7.500000,11.00000,9.500000
50%,4.50000,180140.000000,29.000000,91.000000,92.500000,2201.500000,4.000000,4.000000,4.000000,9.5000,...,80.000000,86.500000,33.500000,29.500000,29.500000,12.000000,11.500000,15.000000,14.00000,11.000000
75%,6.75000,192456.500000,31.750000,91.750000,93.000000,2267.000000,5.000000,4.000000,4.000000,10.0000,...,84.250000,93.250000,61.500000,54.750000,47.750000,24.000000,22.000000,27.000000,28.50000,31.000000
max,9.00000,200389.000000,33.000000,94.000000,94.000000,2346.000000,5.000000,5.000000,5.000000,15.0000,...,86.000000,96.000000,87.000000,92.000000,91.000000,90.000000,92.000000,87.000000,88.00000,94.000000

In [20]:
df.apply(lambda x: sum(x.isnull()), axis=0)

Unnamed: 0                   0
ID                           0
Name                         0
Age                          0
Photo                        0
Nationality                  0
Flag                         0
Overall                      0
Potential                    0
Club                         0
Club Logo                    0
Value                        0
Wage                         0
Special                      0
Preferred Foot               0
International Reputation     0
Weak Foot                    0
Skill Moves                  0
Work Rate                    0
Body Type                    0
Real Face                    0
Position                     0
Jersey Number                0
Joined                       0
Loaned From                 10
Contract Valid Until         0
Height                       0
Weight                       0
LS                           2
ST                           2
                            ..
Dribbling                    0
Curve                        0
FKAccuracy                   0
LongPassing                  0
BallControl                  0
Acceleration                 0
SprintSpeed                  0
Agility                      0
Reactions                    0
Balance                      0
ShotPower                    0
Jumping                      0
Stamina                      0
Strength                     0
LongShots                    0
Aggression                   0
Interceptions                0
Positioning                  0
Vision                       0
Penalties                    0
Composure                    0
Marking                      0
StandingTackle               0
SlidingTackle                0
GKDiving                     0
GKHandling                   0
GKKicking                    0
GKPositioning                0
GKReflexes                   0
Release Clause               0
Length: 89, dtype: int64

In [23]:
df.dtypes

Unnamed: 0                    int64
ID                            int64
Name                         object
Age                           int64
Photo                        object
Nationality                  object
Flag                         object
Overall                       int64
Potential                     int64
Club                         object
Club Logo                    object
Value                        object
Wage                         object
Special                       int64
Preferred Foot               object
International Reputation    float64
Weak Foot                   float64
Skill Moves                 float64
Work Rate                    object
Body Type                    object
Real Face                    object
Position                     object
Jersey Number               float64
Joined                       object
Loaned From                  object
Contract Valid Until         object
Height                       object
Weight                       object
LS                           object
ST                           object
                             ...
Dribbling                   float64
Curve                       float64
FKAccuracy                  float64
LongPassing                 float64
BallControl                 float64
Acceleration                float64
SprintSpeed                 float64
Agility                     float64
Reactions                   float64
Balance                     float64
ShotPower                   float64
Jumping                     float64
Stamina                     float64
Strength                    float64
LongShots                   float64
Aggression                  float64
Interceptions               float64
Positioning                 float64
Vision                      float64
Penalties                   float64
Composure                   float64
Marking                     float64
StandingTackle              float64
SlidingTackle               float64
GKDiving                    float64
GKHandling                  float64
GKKicking                   float64
GKPositioning               float64
GKReflexes                  float64
Release Clause               object
Length: 89, dtype: object